### ISSUE TITLE
current version not runnable through maven

### ISSUE THREAD

**Issue by toby78** [spreadthesource/wooki#103]
Path to dependency:
        1) com.wooki:wooki:war:0.3.0
        2) com.spreadthesource:tapestry5-db-migration:jar:0.1.1-SNAPSHOT
        3) org.apache.tapestry:tapestry-hibernate-core:jar:5.2.0-SNAPSHOT

  org.apache.tapestry:tapestry-hibernate-core:jar:5.2.0-SNAPSHOT

from the specified remote repositories:
  jboss-snapshot (http://snapshots.jboss.org/maven2),
  hibernate (https://repository.jboss.org/nexus/content/groups/public/),
  java.net (http://download.java.net/maven/2/),
  devlab722-snapshot-repo (http://nexus.devlab722.net/nexus/content/repositories
/snapshots),
  fop (http://repo1.maven.org/maven2/org/apache/xmlgraphics/fop),
  apache-snapshots (https://repository.apache.org/content/repositories/snapshots
),
  apache (https://repository.apache.org/content/groups/public/),
  jboss (https://repository.jboss.org/nexus/content/groups/public/),
  codehaus.snapshots (http://snapshots.repository.codehaus.org),
  devlab722-repo (http://nexus.devlab722.net/nexus/content/repositories/releases
),
  repo1 (http://repo1.maven.org/maven2/),
  springsource maven repo (http://maven.springframework.org/milestone),
  OpenQA_Release (http://archiva.openqa.org/repository/releases/)

[INFO] Unable to read jar manifest from C:\Dokumente und Einstellungen\marxt.m2
\repository\org\apache\tapestry\tapestry-hibernate-core\5.2.0-SNAPSHOT\tapestry-
hibernate-core-5.2.0-SNAPSHOT.jar
[INFO] Resource directory's path matches an existing source directory. Resources
 will be merged with the source directory src/main/resources
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Request to merge when 'filtering' is not identical. Original=resource src
/main/resources: output=target/classes, include=[], exclude=[**/*.java], test=fa
lse, filtering=false, merging with=resource src/main/resources: output=target/cl
asses, include=[**/_.properties|__/hibernate.cfg.xml], exclude=[__/_.java], test
=false, filtering=true
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Request to merge when 'f
iltering' is not identical. Original=resource src/main/resources: output=target/
classes, include=[], exclude=[**/*.java], test=false, filtering=false, merging w
ith=resource src/main/resources: output=target/classes, include=[**/_.properties
|__/hibernate.cfg.xml], exclude=[__/_.java], test=false, filtering=true
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:719)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandalone
Goal(DefaultLifecycleExecutor.java:569)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:6
0)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

```
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

Caused by: org.apache.maven.plugin.MojoExecutionException: Request to merge when
 'filtering' is not identical. Original=resource src/main/resources: output=targ
et/classes, include=[], exclude=[**/*.java], test=false, filtering=false, mergin
g with=resource src/main/resources: output=target/classes, include=[**/_.propert
ies|__/hibernate.cfg.xml], exclude=[__/_.java], test=false, filtering=true
        at org.apache.maven.plugin.eclipse.EclipseSourceDir.merge(EclipseSourceD
ir.java:302)
        at org.apache.maven.plugin.eclipse.EclipsePlugin.extractResourceDirs(Ecl
ipsePlugin.java:1605)
        at org.apache.maven.plugin.eclipse.EclipsePlugin.buildDirectoryList(Ecli
psePlugin.java:1490)
        at org.apache.maven.plugin.eclipse.EclipsePlugin.createEclipseWriterConf
ig(EclipsePlugin.java:1180)
        at org.apache.maven.plugin.eclipse.EclipsePlugin.writeConfiguration(Ecli
psePlugin.java:1043)
        at org.apache.maven.plugin.ide.AbstractIdeSupportMojo.execute(AbstractId
eSupportMojo.java:511)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:694)
        ... 17 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 minutes 23 seconds
[INFO] Finished at: Tue Aug 17 16:07:17 CEST 2010
[INFO] Final Memory: 18M/32M
[INFO] ------------------------------------------------------------------------

**Comment by ccordenier** [comment]
Hi
I think I have seen this on the user mailing list, forcing Maven update or cleaning the existing should solve... Anyway i will look further.

**Comment by ccordenier** [comment]
cannot reproduce

**Comment by ccordenier** [comment]
cannot reproduce
